# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'maven'
    mavenServiceConnections: 'arjit_maven'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'deploy'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: CopyFiles@2
  inputs:
    Contents: '*/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: CmdLine@2
  inputs:
    script: |
      cd $(Build.ArtifactStagingDirectory)
      ls -lrth
      cd target
      ls
      mv *.jar ../
      cd ..
      rmdir target/
      ls



- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'artifacts'
    publishLocation: 'Container'

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'arjitks77/maven'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'