# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: variables1
- name: snyk_token
  value: $[variables.SNYKTOKEN]
steps:
- task: Bash@3
  displayName: Integrate SCA using snyk in Azure Devops pipeline
  inputs:
    targetType: 'inline'
    script: |
      SNYK_TOKEN=$(snyk_token) 
      export SNYK_TOKEN
      mvn snyk:test -fy 