# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest



steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonar'
    organization: 'arjitdevops'
    scannerMode: 'Other'
    extraProperties: |
      sonar.projectKey=srivasarjit_DevOps-Project
      sonar.projectName=DevOps Project
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'