# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:
- group: java_pipeline_variables

pool:
  vmImage: $(vm)

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'anshika-sonar'
    organization: 'anshika-job-hunt'
    scannerMode: 'Other'
- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'anshika'
    mavenServiceConnections: 'maven_anshika'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean deploy'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: CopyFiles@2
  inputs:
    Contents: '*/*jar'
    TargetFolder: '$(build.Artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Java_output'
    publishLocation: 'Container'

